spring.application.name=andromeda
PORT = 8080
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.ktjcaqnjfgsmxkljjrrg
spring.datasource.password=PjFaVMz4Lfdpelpb
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true